version: "3.7"
services:
  clientbuilder:
    build:
      context: ./
      dockerfile: ./src/client/Dockerfile
    restart: always
    volumes:
        - "./src/client/dist:/app/dist"
        - "./src/client/src:/app/src"
  clientserver:
    build:
      context: ./
      dockerfile: ./src/client/DockerfileServe
    restart: always
    ports:
        - "4300:5000"
    volumes:
        - "./src/client/dist:/app/dist"
  realtime:
    build:
      context: ./
      dockerfile: ./src/server/realTime/Dockerfile
    restart: always
    ports:
      - "0.0.0.0:2556:2556"
  playerserver:
    build:
      context: ./
      dockerfile: ./src/server/playerServer/Dockerfile
    restart: always
    ports:
      - "0.0.0.0:4552:4552"
      - "0.0.0.0:2552:2552"
  siteplugins:
    build:
      context: ./
      dockerfile: ./src/server/sitePlugins/Dockerfile
    restart: always
    ports:
      - "0.0.0.0:6552:6552"
  loadbalancer:
    build:
      context: ./
      dockerfile: ./src/server/loadBalancer/Dockerfile
    restart: always
    ports:
      - "0.0.0.0:3552:3552"
  imageserver:
    build:
      context: ./
      dockerfile: ./src/server/imageServer/Dockerfile
    restart: always
    ports:
      - "0.0.0.0:5552:5552"
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yQ25*IwPYS*7
      MYSQL_DATABASE: anondraw
    volumes:
#      - ./data/mysql:/var/lib/mysql
      - ./data/configs:/etc/mysql/conf.d
      - ./data/start:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 4400:8080
